### ISSUE TITLE
error initializing listen module

### ISSUE THREAD

**Issue by marciotisouza** [Lyokone/flutterlocation#866] opened 2023-07-29 13:21 UTC
void listLocation() {
    location.changeSettings(
        accuracy: LocationAccuracy.high, distanceFilter: 20, interval: 5000);
    location.onLocationChanged.listen((LocationData currentLocation) {
        print(currentLocation);
    });
  }

E/flutter (11325): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type '_Map<Object?, Object?>' is not a subtype of type 'Map<String, dynamic>' in type cast
E/flutter (11325): #0      MethodChannelLocation.onLocationChanged.<anonymous closure>
method_channel_location.dart:146
E/flutter (11325): #1      _MapStream._handleData (dart:async/stream_pipe.dart:213:31)
E/flutter (11325): #2      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
E/flutter (11325): #3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
E/flutter (11325): #4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (11325): #5      _DelayedData.perform (dart:async/stream_impl.dart:515:14)
E/flutter (11325): #6      _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)

location 5.0.1
Flutter 3.10.5
Dart 3.0.5

**Comment by gyuri-fluttech** [comment] 2023-07-30 14:03
This seems to be a duplicate of:  https://github.com/Lyokone/flutterlocation/issues/863

**Comment by bartekpacia** [comment] 2023-08-04 11:33
Thanks. This is indeed a duplicate of #863

**Closed by bartekpacia** 2023-08-04 11:33 UTC
