### ISSUE TITLE
Location service screen is not showing in HUAWEI w/o Google services

### ISSUE THREAD

**Issue by kostadin24** [Lyokone/flutterlocation#820] opened 2023-03-08 13:42 UTC
I have Huawei with android 11. In the past I was able to show 'Location' system screen by calling 'location.requestService()'.
Now this screen is not appearing anymore.

**Tested on:**
- Huawei with Android, API Level 30 real device, no google services available.

**Additional logs**
W/GooglePlayServicesUtil( 8253): com.xxxxx.xxxxxx requires the Google Play Store, but it is missing.
W/GoogleApiManager( 8253): The service for com.google.android.gms.internal.location.zzaz is not available: ConnectionResult{statusCode=SERVICE_INVALID, resolution=null, message=null}
E/flutter ( 8253): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(SERVICE_STATUS_ERROR, Unexpected error type received, null, null)
E/flutter ( 8253): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
E/flutter ( 8253): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:315:18)
E/flutter ( 8253): <asynchronous suspension>
E/flutter ( 8253): #2      MethodChannelLocation.requestService (package:location_platform_interface/src/method_channel_location.dart:137:25)
E/flutter ( 8253): <asynchronous suspension>

**Comment by wsxc451** [comment] 2023-04-12 02:22
+1

**Comment by kostadin24** [comment] 2023-04-26 16:46
I did change in my project - when no GooglePlay services present - I use alternative source and libs.
All places where mention Huawei - they are commented when build for Google and uncommented when biuld for Huawei :)
Only single script change comments depending platform selected for build

**Comment by bgmf** [comment] 2023-04-28 13:39
I'm not an Android guru by any means, but aren't build flavors supported now? This could be a solution to our struggles, right?

**Comment by bartekpacia** [comment] 2023-08-09 22:47
This looks like a duplicate of #772 (correct me if not).

**Closed by bartekpacia** 2023-08-09 22:47 UTC
Labels: bug
