### ISSUE TITLE
Getting location service status in android throws exception

### ISSUE THREAD

**Issue by rohnsht** [Lyokone/flutterlocation#294] opened 2020-02-24 03:42 UTC
**Describe the bug**
The plugin thrown exception when trying to get the location service status using the function `location.serviceEnabled()` in android in the latest version 2.5.1. Whereas, it was working fine in previous version (2.3.5).

**Expected behavior**

**Tested on:**
 - Android, API Level 28, Samsung galaxy s8 and in Emulator with API Level 29

**Additional logs**

``` E/flutter (23142): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(SERVICE_STATUS_ERROR, Location service status couldn't be determined, null)
E/flutter (23142): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (23142): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
E/flutter (23142): <asynchronous suspension>
E/flutter (23142): #2      Location.serviceEnabled (package:location/location.dart:137:8)
E/flutter (23142): #3      _HomeScreenState._getLocation (package:stampme/screens/home_screen.dart:74:25)
E/flutter (23142): #4      _HomeScreenState.initState (package:stampme/screens/home_screen.dart:51:5)
E/flutter (23142): #5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4355:58)
E/flutter (23142): #6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter (23142): #7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (23142): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (23142): #9      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter (23142): #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (23142): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (23142): #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter (23142): #13     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter (23142): #14     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
E/flutter (23142): #15     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter (23142): #16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (23142): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (23142): #18     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter (23142): #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (23142): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (23142): #21     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter (23142): #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (23142): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (23142): #24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter (23142): #25     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter (23142): #26     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
E/flutter (23142): #27     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
E/flutter (23142): #28     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter (23142): #29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (23142): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (23142): #31     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter (23142): #32     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (23142): #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (23142): #34     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter (23142): #35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (23142): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (23142): #37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter (23142): #38     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter (23142): #39     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
E/flutter (23142): #40     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
E/flutter (23142): #41     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter (23142): #42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (23142): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (23142): #44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter (23142): #45 

```

**Comment by Lyokone** [comment] 2020-02-24 08:10
Can you give logs a couple of line before what you gave, I'm missing the exception

**Comment by richard-gp** [comment] 2020-02-24 10:50
I am also able to replicate in emulator Pixel 2 API 29 as well as Huawei P20 Pro & Huawei P7.

Was working fine in version 2.3.5 but once upgraded to version 2.5.1 it is not able to get location service.

Console during debug mode on emulator shows:
`I/flutter (  667): SERVICE_STATUS_ERROR`

Logcat shows:
`2020-02-24 18:46:58.130 667-714/app.tipme.reclaims I/flutter: SERVICE_STATUS_ERROR`

**Comment by Lyokone** [comment] 2020-02-24 10:55
I'm going to investigate on this,  this is directly linked to this code,
```
        try {
            gps_enabled = this.locationManager.isProviderEnabled(LocationManager.GPS_PROVIDER);
            network_enabled = this.locationManager.isProviderEnabled(LocationManager.NETWORK_PROVIDER);
        } catch (Exception ex) {
            result.error("SERVICE_STATUS_ERROR", "Location service status couldn't be determined", null);
            return false;
        }
```

**Comment by Lyokone** [comment] 2020-02-24 11:35
I cannot reproduce this error with the example app. 
Is your app older than Flutter 1.12 ? You may need to apply this guide : https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects

**Comment by rohnsht** [comment] 2020-02-24 11:50
Sorry, about the above log. I missed the important part. Here is the log you asked for:
`[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(SERVICE_STATUS_ERROR, Location service status couldn't be determined, null)`

and here is my flutter details
`[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale en-AU)
    • Flutter version 1.12.13+hotfix.8 at /Users/rohan/Development/flutter
    • Framework revision 0b8abb4724 (13 days ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0`

**Comment by malavdesai-rirev** [comment] 2020-02-25 12:21
I am facing the same issue after upgrading to 2.5.1

**Comment by Lyokone** [comment] 2020-02-25 12:24
> I cannot reproduce this error with the example app.
> Is your app older than Flutter 1.12 ? You may need to apply this guide : https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects

Have you tried this @malavdesai-rirev  ?

**Comment by Lyokone** [comment] 2020-02-25 12:32
I've upgrade the plugin to 2.5.2 with a fix for pre-1.12 projects, please tell me if it fixes your issue :)

**Comment by DebkanchanSamadder** [comment] 2020-02-25 15:23
Tested on Pixel 3a XL Emulator with Android R. Works perfectly. However doesn't work on real device but it is due to fault in device. So real device test result is inconclusive.

**Comment by malavdesai-rirev** [comment] 2020-02-26 06:17
@Lyokone I have made some changes based on https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects and now it's working. But i have not updated plugin to 2.5.2.

**Comment by Lyokone** [comment] 2020-02-26 08:02
Great ! I'll be closing this if it's fixed 😁

**Closed by Lyokone** 2020-02-26 08:02 UTC
Labels: bug

**Comment by richard-gp** [comment] 2020-02-26 09:26
> I've upgraded the plugin to 2.5.2 with a fix for pre-1.12 projects, please tell me if it fixes your issue :)

Yes it works brilliantly

**Comment by GiacomoK** [comment] 2020-03-03 18:25
I still get this error with version 2.5.3

This is the error I get on sentry:

    PlatformException: PlatformException(SERVICE_STATUS_ERROR, Location service status couldn't be determined, null)
    File "message_codecs.dart", line 569, in StandardMethodCodec.decodeEnvelope
    File "platform_channel.dart", line 321, in MethodChannel.invokeMethod
    File "<asynchronous suspension>"
    File "location.dart", line 137, in Location.serviceEnabled

**Comment by lessthanno** [comment] 2020-03-09 12:21
> I still get this error with version 2.5.3
> 
> This is the error I get on sentry:
> 
> ```
> PlatformException: PlatformException(SERVICE_STATUS_ERROR, Location service status couldn't be determined, null)
> File "message_codecs.dart", line 569, in StandardMethodCodec.decodeEnvelope
> File "platform_channel.dart", line 321, in MethodChannel.invokeMethod
> File "<asynchronous suspension>"
> File "location.dart", line 137, in Location.serviceEnabled
> ```

the same bug

**Comment by amreniouinnovent** [comment] 2020-06-11 10:01
same on 3.0.2

**Comment by amreniouinnovent** [comment] 2020-06-11 10:18
My case related to Airplane mode cannot show enable GPS service
