### ISSUE TITLE
UIAlertViewfix: 

### ISSUE THREAD

**Issue by im-pch** [Lyokone/flutterlocation#765] opened 2022-09-28 23:53 UTC
**Description**
Flutter clean was run, but bug is still showing and preventing build.
**Expected behavior**
Should have completed build, flutter was upgraded two days ago and was working fine before. 
**Steps To Reproduce**

Flutter clean and flutter run on iOS simulator device

Writing result bundle at path:
    	/var/folders/dt/ymx6cbj16xq_flrs8l2xzc9r0000gn/T/flutter_tools.rzO49o/flutt
    	er_ios_build_temp_dirHHxj9c/temporary_xcresult_bundle

    /Users/rohan/.pub-cache/hosted/pub.dartlang.org/location-4.4.0/ios/Classes/L
    ocationPlugin.m:176:13: warning: 'UIAlertView' is deprecated: first
    deprecated in iOS 9.0 - UIAlertView is deprecated. Use UIAlertController
    with a preferredStyle of UIAlertControllerStyleAlert instead
    [-Wdeprecated-declarations]
                UIAlertView *alert = [[UIAlertView alloc]
                initWithTitle:@"Location is Disabled"
                ^
    In module 'UIKit' imported from
    /Users/rohan/Downloads/jakstatcourier/ios/Pods/Target Support
    Files/location/location-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platfor
    m/Developer/SDKs/iPhoneSimulator15.2.sdk/System/Library/Frameworks/UIKit.fra
    mework/Headers/UIAlertView.h:27:12: note: 'UIAlertView' has been explicitly
    marked deprecated here
    @interface UIAlertView : UIView
               ^
    /Users/rohan/.pub-cache/hosted/pub.dartlang.org/location-4.4.0/ios/Classes/L
    ocationPlugin.m:176:48: warning: 'UIAlertView' is deprecated: first
    deprecated in iOS 9.0 - UIAlertView is deprecated. Use UIAlertController
    with a preferredStyle of UIAlertControllerStyleAlert instead
    [-Wdeprecated-declarations]
                UIAlertView *alert = [[UIAlertView alloc]
                initWithTitle:@"Location is Disabled"
                                                   ^
    In module 'UIKit' imported from
    /Users/rohan/Downloads/jakstatcourier/ios/Pods/Target Support
    Files/location/location-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platfor
    m/Developer/SDKs/iPhoneSimulator15.2.sdk/System/Library/Frameworks/UIKit.fra
    mework/Headers/UIAlertView.h:27:12: note: 'UIAlertView' has been explicitly
    marked deprecated here
    @interface UIAlertView : UIView
               ^
    2 warnings generated.
    /Users/rohan/.pub-cache/hosted/pub.dartlang.org/location-4.4.0/ios/Classes/L
    ocationPlugin.m:176:13: warning: 'UIAlertView' is deprecated: first
    deprecated in iOS 9.0 - UIAlertView is deprecated. Use UIAlertController
    with a preferredStyle of UIAlertControllerStyleAlert instead
    [-Wdeprecated-declarations]
                UIAlertView *alert = [[UIAlertView alloc]
                initWithTitle:@"Location is Disabled"
                ^
    In module 'UIKit' imported from
    /Users/rohan/Downloads/jakstatcourier/ios/Pods/Target Support
    Files/location/location-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platfor
    m/Developer/SDKs/iPhoneSimulator15.2.sdk/System/Library/Frameworks/UIKit.fra
    mework/Headers/UIAlertView.h:27:12: note: 'UIAlertView' has been explicitly
    marked deprecated here
    @interface UIAlertView : UIView
               ^
    /Users/rohan/.pub-cache/hosted/pub.dartlang.org/location-4.4.0/ios/Classes/L
    ocationPlugin.m:176:48: warning: 'UIAlertView' is deprecated: first
    deprecated in iOS 9.0 - UIAlertView is deprecated. Use UIAlertController
    with a preferredStyle of UIAlertControllerStyleAlert instead
    [-Wdeprecated-declarations]
                UIAlertView *alert = [[UIAlertView alloc]
                initWithTitle:@"Location is Disabled"
                                                   ^
    In module 'UIKit' imported from
    /Users/rohan/Downloads/jakstatcourier/ios/Pods/Target Support
    Files/location/location-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platfor
    m/Developer/SDKs/iPhoneSimulator15.2.sdk/System/Library/Frameworks/UIKit.fra
    mework/Headers/UIAlertView.h:27:12: note: 'UIAlertView' has been explicitly
    marked deprecated here
    @interface UIAlertView : UIView
               ^
----

Could not build the application for the simulator.
Error launching application on iPhone 13.

**Comment by bartekpacia** [comment] 2023-10-03 11:09
duplicate of #505

**Closed by bartekpacia** 2023-10-03 11:09 UTC
Labels: bug
