### ISSUE TITLE
Deprecated

### ISSUE THREAD

**Issue by blondie63** [Lyokone/flutterlocation#903] opened 2023-09-28 10:30 UTC
Is there a plan to fix these?
<img width="563" alt="xcode_location_5 0 3_deprecated" src="https://github.com/Lyokone/flutterlocation/assets/1261851/9caa31d0-193d-4d40-973e-a0e84d0fb0cb">

**Comment by bartekpacia** [comment] 2023-10-03 11:09
duplicate of #505

**Closed by bartekpacia** 2023-10-03 11:09 UTC
