### ISSUE TITLE
 FATAL EXCEPTION: pool-21-thread-5

### ISSUE THREAD

**Issue by Vish88781** [Lyokone/flutterlocation#807] opened 2023-02-01 08:09 UTC
I/flutter (17569): ********* startBackgroundTask: 1
E/AndroidRuntime(17569): FATAL EXCEPTION: pool-21-thread-5
E/AndroidRuntime(17569): Process: package name, PID: 17569
E/AndroidRuntime(17569): java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in /data/app/~~itAWtDwAr7olrA6oQ9ShHQ==/package name -2rKjSQ0BDOE7dI-qaG6cnw==/base.apk)
E/AndroidRuntime(17569): at com.transistorsoft.locationmanager.location.SingleLocationRequest.startUpdatingLocation(Unknown Source:123)
E/AndroidRuntime(17569): at com.transistorsoft.locationmanager.service.LocationRequestService.handleStartAction(Unknown Source:74)
E/AndroidRuntime(17569): at com.transistorsoft.locationmanager.service.LocationRequestService.access$200(Unknown Source:0)
E/AndroidRuntime(17569): at com.transistorsoft.locationmanager.service.LocationRequestService$a.run(Unknown Source:62)
E/AndroidRuntime(17569): at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(17569): at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(17569): at java.lang.Thread.run(Thread.java:923)
D/AppCompatDelegate(17569): Checking for metadata for AppLocalesMetadataHolderService : Service not found
D/AndroidRuntime(17569): Shutting down VM
E/AndroidRuntime(17569): FATAL EXCEPTION: main
E/AndroidRuntime(17569): Process: Package name, PID: 17569
E/AndroidRuntime(17569): java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.SettingsClient, but class was expected (declaration of 'com.google.android.gms.location.SettingsClient' appears in /data/app/~~itAWtDwAr7olrA6oQ9ShHQ==/package name-2rKjSQ0BDOE7dI-qaG6cnw==/base.apk)

**Comment by bartekpacia** [comment] 2023-08-04 14:01
Likely a duplicate of #805 (and a few others).

**Closed by bartekpacia** 2023-08-04 14:01 UTC
Labels: bug
