### ISSUE TITLE
fix: kotlin version mismatch with sdk-enviroment in pubspec.yaml file 

### ISSUE THREAD

**Issue by AakibKhilji9286** [Lyokone/flutterlocation#843] opened 2023-05-24 04:58 UTC
environment:
  sdk: '>=3.0.1 <4.0.0'

location: ^4.4.0

FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':location' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.20

getting this error while importing location plugin.
my kotlin version 1.7.10 it is already updated.
what is the solution of it?

**Comment by ToddBrawn** [comment] 2023-05-24 12:50
Same issues compiling for Android using current location version [4.4.0](https://pub.dev/packages/location/versions/4.4.0)

**Comment by AnByronV** [comment] 2023-05-24 14:45
I have the same issue

**Comment by hamis030** [comment] 2023-05-24 17:46
Same Here

**Comment by hamis030** [comment] 2023-05-24 17:56
A temporary fix can be found here:
https://github.com/Lyokone/flutterlocation/issues/838#issuecomment-1546739392
It worked for me.

**Comment by as1605** [comment] 2023-06-10 07:08
Go to `~/.pub-cache/hosted/pub.dev/location-4.4.0/android/build.gradle` and change `ext.kotlin_version` from **1.4.20** to **1.7.10** (or whatever is in your project's build.gradle)

**Comment by Prashantsdev** [comment] 2023-06-16 21:35
I'm also facing this issue, author please fix this

**Comment by nasir447** [comment] 2023-06-22 16:51
any fix?

**Comment by nasir447** [comment] 2023-06-22 19:38
> @nasir447 Actually v5 of this package would fix the issue, but it has not been released as stable yet, so only option is to either patch it manually or create a fork of this

I need to use smooth_compass: 2.0.17 something but it uses this location package and this is causing error so...

**Comment by Shabeebcp** [comment] 2023-06-24 03:58
add This In Your Gradle File 

**rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
        configurations.all{
            resolutionStrategy{
             force "com.google.android.gms:play-services-location:21.0.1"
         }
 }
    }
}**

**Comment by bartekpacia** [comment] 2023-07-09 00:17
Duplicate of #838.

**Closed** 2023-07-09 00:31 UTC
Labels: bug
