### ISSUE TITLE
Build on and support Android 12 (SDK 31), i.e. use FLAG_IMMUTABLE for PendingIntent

### ISSUE THREAD

**Issue by PieterAelse** [Lyokone/flutterlocation#639] opened 2021-09-28 13:30 UTC
**Describe the bug**
When building an app using `location`on Android 12 (SDK 31) there's a runtime crash because the `PendingIntent` needs to have a flag for its (im)mutability.

**Expected behavior**
Plugin to not break an app when building on Android 12.

**Tested on:**
 - Android, API Level 31, Google Pixel 3a
 - Android, API Level 31, Google Pixel 5

**Additional logs**
``` shell
2021-09-28 13:51:59.445 26410-26505/com.philips.lighting.hue2.daily E/AndroidRuntime: FATAL EXCEPTION: pool-19-thread-1
    Process: [redacted_applicaton_id], PID: 26410
    java.lang.IllegalArgumentException: [redacted_applicaton_id]: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
        at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
        at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
        at androidx.work.impl.utils.ForceStopRunnable.getPendingIntent(ForceStopRunnable.java:273)
        at androidx.work.impl.utils.ForceStopRunnable.isForceStopped(ForceStopRunnable.java:151)
        at androidx.work.impl.utils.ForceStopRunnable.forceStopRunnable(ForceStopRunnable.java:171)
        at androidx.work.impl.utils.ForceStopRunnable.run(ForceStopRunnable.java:102)
        at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
```

**Comment by bartekpacia** [comment] 2023-08-04 14:02
Likely a duplicate of #702.

**Closed by bartekpacia** 2023-08-04 14:02 UTC
