### ISSUE TITLE
Android Exception when asking for Location

### ISSUE THREAD

**Issue by awhitford** [Lyokone/flutterlocation#297] opened 2020-02-24 20:30 UTC
I am now seeing this with **Android** emulator; I'm using **version 2.5.1**:

> E/MethodChannel#lyokone/location( 4136): Failed to handle method call
> E/MethodChannel#lyokone/location( 4136): java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.gms.tasks.Task com.google.android.gms.location.SettingsClient.checkLocationSettings(com.google.android.gms.location.LocationSettingsRequest)' on a null object reference
> E/MethodChannel#lyokone/location( 4136): 	at com.lyokone.location.FlutterLocation.startRequestingLocation(FlutterLocation.java:374)
> E/MethodChannel#lyokone/location( 4136): 	at com.lyokone.location.MethodCallHandlerImpl.onGetLocation(MethodCallHandlerImpl.java:102)
> E/MethodChannel#lyokone/location( 4136): 	at com.lyokone.location.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:33)
> E/MethodChannel#lyokone/location( 4136): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
> E/MethodChannel#lyokone/location( 4136): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
> E/MethodChannel#lyokone/location( 4136): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
> E/MethodChannel#lyokone/location( 4136): 	at android.os.MessageQueue.nativePollOnce(Native Method)
> E/MethodChannel#lyokone/location( 4136): 	at android.os.MessageQueue.next(MessageQueue.java:325)
> E/MethodChannel#lyokone/location( 4136): 	at android.os.Looper.loop(Looper.java:142)
> E/MethodChannel#lyokone/location( 4136): 	at android.app.ActivityThread.main(ActivityThread.java:6494)
> E/MethodChannel#lyokone/location( 4136): 	at java.lang.reflect.Method.invoke(Native Method)
> E/MethodChannel#lyokone/location( 4136): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
> E/MethodChannel#lyokone/location( 4136): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

I am getting this with multiple emulators.  It is reproducible with:
* Pixel 3a API 28 / Play Store / 1080 x 2220: 440 dpi / API 28 / Android 9.0 (Google Play)
* Lenovo Tab E7 / 600 x 1024: mdpi / API 27 / Android 8.1 (Google APIs)

**Comment by dustymugs** [comment] 2020-02-24 22:29
I'm seeing this with the same exception. Of the stacktrace bits that matter:

```
E/flutter (13478): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'com.google.android.gms.tasks.Task com.google.android.gms.location.SettingsClient.checkLocationSettings(com.google.android.gms.location.LocationSettingsRequest)' on a null object reference, null)
E/flutter (13478): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (13478): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
E/flutter (13478): <asynchronous suspension>
E/flutter (13478): #2      Location.getLocation (package:location/location.dart:96:31)
```

This is with location == 2.3.5

**Comment by awhitford** [comment] 2020-02-24 22:35
For me, reverting to location 2.3.5 worked; you may want to double check that you are using 2.3.5 by checking your `pubspec.lock` file.  I had to specify **2.3.5**, not **^2.3.5**, and do a `flutter clean` to ensure that I downgraded.

**Comment by Lyokone** [comment] 2020-02-25 07:47
Hey ! I think I haven't made it clear enough in the Changelog, but the 2.5 release is with the new Android Embedding, if you have not upgraded your app (https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects) the plugin will not work properly.
You should consider this upgrade as the old Embedding is now deprecated.

**Comment by Lyokone** [comment] 2020-02-25 07:48
I'm closing this since the issues are normal for pre 1.12 projects :)

**Closed by Lyokone** 2020-02-25 07:48 UTC

**Comment by awhitford** [comment] 2020-02-25 07:52
Thanks for the tip -- I will try that.

But I didn't see any mention of this in the [Change Log](https://pub.dev/packages/location#-changelog-tab-) or [ReadMe](https://pub.dev/packages/location#-readme-tab-).

**Comment by Lyokone** [comment] 2020-02-25 08:06
My bad, forgot to add it, sorry about that. 
Feel free to reopen this issue if the problem is still present after upgrading your project :)

**Comment by awhitford** [comment] 2020-02-25 19:17
It appears to be working after following the upgrade instructions.  Thanks!
