### ISSUE TITLE
fix: Want this library to work in background when application is killed

### ISSUE THREAD

**Issue by Hiral-Bhojani** [Lyokone/flutterlocation#836] opened 2023-05-03 13:14 UTC
**Description**
A clear and concise description of what the bug is. Have you tried running `flutter clean` first ?

**Expected behavior**

**Steps To Reproduce**

**Tested on:**

- Android, API Level XX [e.g. 31], simulator or real device
- iOS, Version XX [e.g. 15], simulator or real device

**Other plugins:**

- List of others Flutter plugins that could interfere

**Additional logs**

```shell
some logs
```

**Comment by ijogendrajat** [comment] 2023-07-06 17:56
Same for me when app is closed this package don't update any data from location.

**Comment by xunreal75** [comment] 2023-07-06 18:19
Therefore you need an separate to configure background task. It's not possible and not planned and not a bug.

Closing an app is killing and quit location service also.
Running in background is the intention of the package. 

If you kill google maps navigation app, there is your location killed too.

**Comment by bartekpacia** [comment] 2023-07-10 16:35
As said above by @xunreal75, this is not possible

**Closed by bartekpacia** 2023-07-10 16:35 UTC
Labels: bug
