### ISSUE TITLE
location_platform_interface error on 5.0.1

### ISSUE THREAD

**Issue by keskink** [Lyokone/flutterlocation#867] opened 2023-07-30 17:51 UTC
I am getting error as below.

 [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type '_Map<Object?, Object?>' is not a subtype of type 'Map<String, dynamic>' in type cast

E/flutter ( 3721): #0      MethodChannelLocation.onLocationChanged.<anonymous closure> (package:location_platform_interface/src/method_channel_location.dart:146)
E/flutter ( 3721): #1      _MapStream._handleData (dart:async/stream_pipe.dart:213)
E/flutter ( 3721): #2      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153)
E/flutter ( 3721): #3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594)
E/flutter ( 3721): #4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339)
E/flutter ( 3721): #5      _DelayedData.perform (dart:async/stream_impl.dart:515)
E/flutter ( 3721): #6      _PendingEvents.handleNext (dart:async/stream_impl.dart:620)
E/flutter ( 3721): #7      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591)
E/flutter ( 3721): #8      _microtaskLoop (dart:async/schedule_microtask.dart:40)
E/flutter ( 3721): #9      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)
E/flutter ( 3721):

**Comment by komaxx** [comment] 2023-07-31 09:14
Same here :/

**Comment by bhanuka96** [comment] 2023-07-31 10:18
Same issue.

**Comment by komaxx** [comment] 2023-08-01 12:37
This is probably a duplicate of #863

**Comment by YassineChe** [comment] 2023-08-01 13:23
Same issue!!!

**Comment by fabiolindemberg** [comment] 2023-08-02 23:33
I'm still facing this error as well, here is additional information, I hope it helps.

_[CoreLocation] This method can cause UI unresponsiveness if invoked on the main thread. Instead, consider waiting for the `-locationManagerDidChangeAuthorization:` callback and checking `authorizationStatus` first._

Maybe the message above is the real reason why the routine is failing. This is happening during the execution of the method: Location.instance.enableBackgroundMode(). I guess it will be necessary to ensure it runs in a secondary thread.

**Comment by komaxx** [comment] 2023-08-03 09:15
@fabiolindemberg That sounds like a different issue, I think. 
I've observed the encoding decoding issues on Android. My guess is that the issue is somewhere in the Dart layer of the plugin - at least, that's how this `Map` type mismatch looks to me.

**Comment by KonstantinRr** [comment] 2023-08-04 06:57
I’m having the same issue on iOS.

**Comment by bartekpacia** [comment] 2023-08-04 11:36
Duplicate of #863.

**Closed by bartekpacia** 2023-08-04 11:36 UTC
