### ISSUE TITLE
IncompatibleClassChangeError FusedLocationProviderClient with latest commit

### ISSUE THREAD

**Issue by mateoKutnjak** [Lyokone/flutterlocation#805] opened 2023-01-30 22:51 UTC
This is my entry in pubspec.yaml

```
location:
    git:
      url: https://github.com/Lyokone/flutterlocation.git
      ref: f9c1051ad3b4edfeb5574395f3bdabe5bef789f8 # branch name
      path: packages/location
```

And this is the error

```
E/AndroidRuntime(17136): 	at com.lyokone.location.location.LocationManager.permissionGranted(LocationManager.java:255)
E/AndroidRuntime(17136): 	at com.lyokone.location.location.LocationManager.askForPermission(LocationManager.java:233)
E/AndroidRuntime(17136): 	at com.lyokone.location.location.LocationManager.get(LocationManager.java:221)
E/AndroidRuntime(17136): 	at com.lyokone.location.LocationPlugin.onListen(LocationPlugin.kt:541)
E/AndroidRuntime(17136): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onListen(EventChannel.java:218)
E/AndroidRuntime(17136): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onMessage(EventChannel.java:197)
E/AndroidRuntime(17136): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/AndroidRuntime(17136): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/AndroidRuntime(17136): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/AndroidRuntime(17136): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime(17136): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime(17136): 	at android.os.Looper.loop(Looper.java:237)
E/AndroidRuntime(17136): 	at android.app.ActivityThread.main(ActivityThread.java:8167)
E/AndroidRuntime(17136): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(17136): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
E/AndroidRuntime(17136): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
2
I/System.out(17136): (HTTPLog)-Static: isSBSettingEnabled false
I/Process (17136): Sending signal. PID: 17136 SIG: 9
Lost connection to device.
```

**Comment by jithware** [comment] 2023-01-31 13:13
Possible duplicate of #804

**Comment by giorgio79** [comment] 2023-01-31 23:01
https://github.com/Lyokone/flutterlocation/issues/802

**Comment by LaxmikanthMadhyastha** [comment] 2023-02-01 15:48
Try [this](https://github.com/Lyokone/flutterlocation/issues/804#issuecomment-1412259071) temporary fix

**Comment by giroprotagonist** [comment] 2023-02-14 17:22
I was getting this using Geolocator 9.0.2, I downgraded to 8.2.1 and it got rid of the error.

**Comment by bartekpacia** [comment] 2023-08-04 13:59
This is fixed in the latest v5 versions.

**Closed by bartekpacia** 2023-08-04 13:59 UTC
Labels: bug
